name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.83
# Disabled because of warning from analyzer
# authors:
#  - Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  wakelock:
    git:
      url: https://github.com/sasen98/wakelock
      path: wakelock

  meta: ^1.15.0

  # flutter_widget_from_html: ^0.14.9
  flutter_widget_from_html:
    git:
      url: https://github.com/sasen98/flutter_widget_from_html/
      path: packages/core

  visibility_detector: ^0.4.0+2
  path_provider: ^2.1.4
  collection: ^1.18.0
  xml: ^6.5.0

dependency_overrides:
  collection: ^1.18.0

dev_dependencies:
  lint: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_localization: ^0.2.2

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin
